export enum ECODES {
  TEAM_ID_MISSING,
  USER_ID_MISSING,
  USER_EMAIL_MISSING,
  USER_NOT_FOUND,
  SESSION_TOKEN_MISSING,
  SESSION_TOKEN_INVALID,
  SESSION_TOKEN_EXPIRED,
}

export const ECODES_TYPE_NAME = "ECODE";
